free_text_columns = ['main_referral_diagnosis' , 'other_diagnoses', 'patient_history',
                     'initial_radiology_report', 'summary_decision_further_strategy', 
                       'radiology_report']

relevant_features = {
    
    'patient_info': {
        'patient_id':'Patient ID (PID)',
        'external_pid':'External PID',
        'fid':'Case number (FID)',
        'clinic_nr':'Clinic no.',
        'entry_date':'Entry date (dd.mm.yyyy)',
        'newest_date_of_sarcomaboard':'Newest Date of SarcomaBoard',
        'year_of_birth':'Year of birth (yyyy)',
        'gender':'Gender', 
        'age_at_admission':'Age: Admission Date minus 1 July of the year of birth (calculated)'
        
    },


    'initial_diagnosis': {
        'initial_size_a': 'Initial size A (in mm)',
        'initial_size_b':'Initial size B (in mm)',
        'initial_size_c':'Initial size C (in mm)',
        'location_initial_lesion':'Location of initial lesion?',
    },


    'dates' : [
    'Date of biopsy (lowest of 806)',
    'Date of first local recurrence (lowest of 666A)',
    'Date of initial radiology exam (lowest)',
    'Date of pathology report (lowest of 1143)',
    'Date of surgery (lowest of 717)',
    'Date of first local recurrence (at follow up) (lowest of 666)',
    'Date of first local recurrence (lowest of 666 and 666A)',
    'Date of last patient contact/information (highest of 725)',
    'Date (highest of 725 and 100 copied to A0)',
    'Date of SarcomaBoard presentation (highest 100)',
    'Entry date (dd.mm.yyyy)',
    'Newest Date of SarcomaBoard',
    # 'Date of surgery',
    'Date of Surgery (dd.mm.yyyy)',
    '100A: Date of SarcomaBoard presentation (100 copied if 6581=yes)',
    'Number of days from first contact with patient to date of SarcomaBoard presentation (calculated)',
    'QI-5: Number of days from date of biopsy to presentation (calculated)',
    'Date of whoops surgery',
    'Date of surgery outside SSN (completed therapy)',
    'Date of radiotherapy outside SSN (completed therapy)',
    'Date of chemotherapy outside SSN (completed therapy)',
    'Date of initial diagnosis',
    'Get Lowest Date of Date of initial radiology',
    'Calculate Date Diff biopsy/radiology (calculated)',
    'Date of initial radiology exam',
    'Date of local recurrence',
    'Date of biopsy',
    'Date of last patient contact/information',
    'Date of last patient contact/information (berechnet)',
    'Date of pathology report (lowest of 1143)',
    ]
    ,
    'outcomes': [
        'QI-1: radiology before biopsy? (calculated)',
        'QI-2: Time (in days) from 1st patient contact to biopsy',
        'QI-17.1: Metastasis at inital presentation exists',
        'QI-17.2: Metastasis at FollowUp exists',
        'QI-18: Status at last patient contact/information (dort wo höchstes Datum 725)',
        'QI-16: Local recurrence within 1st year of tumor resection (Bone)',
        'QI-6: Biopsy was before first treatment per patient',
        'QI-9: Time (in days) from SarcomaBoard until initiation of treatment',
        'QI-15: local relapse? (calculated)',
        'QI-13: Reason for chemotherapy / systemic treatment (calculated)',
        'QI-14: Reason for chemotherapy / systemic treatment (calculated)',
        'QI-3: Number of biopsies',
        'QI-5: Time (in days) from biopsy until SarcomaBoard presentation',
        'QI-4: Time from biopsy to establishing diagnosis (in days)',
        'QI-7: Was the biopsy performed in the same center where the patient was operated?',
        'QI-1: preoperative radiation therapy? (Patient)',
        'Number of recurrence 1st, 2nd, 3rd', 
        'Location of further systemic recurrence',
        'Number of intervention: How many interventions does the case count? (calculated)',
        'Number of operations: How many operations does the case count? (calculated)', 
        'prior diagnostics/treatment outside and systemic recurrence / metastasis (619=3 and 1115=3)',
        'Metastasis at initial presentation',
        'Summary files (upload)',
        'Status',
        'Status at last patient contact/information', 

        'Specify treatment outside SwissSarcomaNetwork',
        'Type of initial radiology exam',
        'QI-6: biopsy before treatment? (calculated)',
        'QI-1.1: Initial radiology report existing? (calculated)',
        'Best treatment response', 
        "Surgeon's judgement of resected tumor margin",
    ],
    'status_metrics': {
        
        
    },



    'operations_n': [
        'Op-No.',        
        # 'Date of surgery',
        'Difference (in days) of local recurrence and tumor resection',
        'Difference (in days) of First Treatment and biopsy',
        'Difference (in days) of First Treatment 15184 and 100A',
        'Biopsy before first treatment',
        'Drug therapy duration (calculated)',
        'Was the biopsy performed in the same center where the patient was operated?',
        'Please specify "other institution"',
        'Please specify other other chest / lung resection (resC.10)',
        'Please specify other treatment outside SSN',
        'Please specify other STS resection (resA.13)',
        'Please specify other sequelae of 1° treatment (resE.11)',
        'Please specify other bone resection (resB.86)',
        'Reconstruction codes',
        'Specify current status',
        'Resection codes',
        'Start of RadOnc',
        'Date of Surgery (dd.mm.yyyy)',
        'End of RadOnc',
        'Surgery number',
        'QI-11: Reason for radiation therapy preoperative (calculated)',
        'QI-12: Reason for radiation therapy postoperative (calculated)',
        'Date of whoops surgery',
        'Reason for radiation therapy',
        'Date of surgery outside SSN (completed therapy)',
        'Date of radiotherapy outside SSN (completed therapy)',
        'Date of chemotherapy outside SSN (completed therapy)',
        'Date of surgery outside SSN (partial therapy)',
        'Date of radiotherapy outside SSN (partial therapy)',
        'Date of chemotherapy outside SSN (partial therapy)',
        'Please specify other abdominal resection (resD.15)',
        'If other therapy outside SSN, please specify (completed therapy):',
        'Type of treatment outside SwissSarcomaNetwork (completed therapy)',
        'Please specify other tendon transfer (recB.11)',
        'Please specify other perforator flap (recB.9)',
        'Please specify other vessel reconstruction (recF.6)',
        'Please specify other nerve reconstruction (recG.1)',
        'Please specify other autologous nerve reconstruction (recG.31)',
        'Please specify other free tissue transfer (recC.5)',
        'Please specify other muscle flap (recB.10)',
        'Please specify other intrathoracic (D19.4.5.)',
        'Please specify other bone reconstruction (recD.14)',
        'Please specify other metastasis (M.13.)',
        'Please specify other intraabdominal reconstruction (recI.6)',
        'Please specify other tumor simulator (0)',
        'Please specify other perforator flap (recC.4)',
        'Please specify other sequelae of 1° treatment (recE.7)',
        'Please specify other extrapelvic anatomic region (D10.2)',
        'Please specify other extrapelvic anatomic region (D10.2) (SB)',
        'Please specify other intrapelvic anatomic region (D10.4)',
        'Please specify other intrapelvic anatomic region (D10.4) (SB)',
        'Please specify other if both intra-/extrapelvic anatomic region (D10.6.3)',
        'Please specify other if both intra-/extrapelvic anatomic region (D10.6.3)',
        'Please specify other if both intra-/extrapelvic anatomic region (D10.6.3) (SB)',
        'Please choose therapy for data entry:',
        'Please specify other institution', 
        'Please specify other perforator flap (recB.9)',
        'Please specify other muscle flap (recB.10)',
        'Anatomic Region Code Surgery', 
        'Total dose: How many Grays?',
        'Treatment at which institution?',
        'Please specify other free tissue transfer (recC.5)',
        'Type of treatment outside SwissSarcomaNetwork (partial therapy)',
        '806A: Date of biopsy (806 copied if 6581=yes)',
        'Date of radiotherapy outside SSN (completed therapy)',
        'Date of chemotherapy outside SSN (completed therapy)',
        'Date of chemotherapy outside SSN (partial therapy)',

        'Additional, and concurrent treatments:',
        'Number of sessions',
        'Temperature',
        'Duration of session (in minutes)',
        'Planning / color wash (upload)',
        'Type of hyperthermia',
        'Comments',
        'Comments (radiation oncologist)',
        'Date of resection',
        'Name of substances?',
                'Number of cycles planned',
        'Number of cycles executed',
        'Reason for discontinuation:',
        'Other substance',
        'Number of intervention: How many interventions does the operation count? (calculated)',
        'Complexity of surgery / Involved disciplines',
        'Start of chemotherapy / systemic treatment',
        'End of chemotherapy / systemic treatment',
        'Radiation therapy duration (calculated)',
        'Report for chemotherapy (upload)',
        'Report for radiation oncology (upload)',
        'Report for surgery (upload)',
        'Surgeon',
        'Comments (chemotherapy)',
        'Report for radiation oncology (upload)', 
        'Type of radiation therapy'
        ],

    'radiology': 
        {
            'entry_type': '*diagnosis',
            'date': 'Date of initial radiology exam',
            'type': '*radiology',
            'details': {
                'initial_report': 'Initial radiology report',
                'size_a': 'Initial size A (in mm)',
                'size_b': 'Initial size B (in mm)',
                'size_c': 'Initial size C (in mm)',
                'location': 'Location of initial lesion',
                'additional_exams': 'Record additional radiology exams',
                'date_of_exam': 'Date of initial radiology exam'
            },
            'radiology_additional': 
                {
                    'date': 'Date of additional radiology exam',
                    'type': 'Type of radiology exam',
                    'report': 'Radiology report (important for SB)',
                    'size_a': 'Size A (in mm)',
                    'size_b': 'Size B (in mm)',
                    'size_c': 'Size C (in mm)'
                },
            'main_referral_diagnosis_ner':'main_referral_diagnosis_ner',  
            'other_diagnoses_ner':'other_diagnoses_ner',
            'patient_history_ner': 'patient_history_ner',
            'initial_radiology_report_ner':'initial_radiology_report_ner', 
            'summary_decision_further_strategy_ner':'summary_decision_further_strategy_ner', 
            'radiology_report_ner': 'radiology_report_ner'

        },
    
    'biopsy': 
        {
            'entry_type': '*diagnosis',
            'date': 'Date of biopsy',
            'type': '*biopsy',
            'details': {
                    'neo_adjuvant': 'Neo-adjuvant / preoperative therapy?',

                'mib_of_sarcoma': 'Proliferation index Mib if sarcoma (%)',
                'mitotic': 'Mitotic count',
                'necrosis': 'Extent of necrosis in %',
                'grading': 'Grading of biopsy',
                'who': 'WHO Diagnosis Code (pathology)',
                'report': 'Pathology report (important for SB)',
                'report_ner': 'pathology_report_important_for_sb_ner'
            },
            'report_ner': 'report_pathologist_biopsy_upload_ner',
            'main_referral_diagnosis_ner':'main_referral_diagnosis_ner',  
            'other_diagnoses_ner':'other_diagnoses_ner',
            'patient_history_ner': 'patient_history_ner',
            'initial_radiology_report_ner':'initial_radiology_report_ner', 
            'summary_decision_further_strategy_ner':'summary_decision_further_strategy_ner', 
            'radiology_report_ner': 'radiology_report_ner'
        },

    'resection_specimen': {
            'entry_type': '*therapy',
            'date': 'Date of resection',
            'type': '*resection',
            'details': {
                'date_pathology': 'Date of pathology report',
                'neo_adjuvant': 'Neo-adjuvant / preoperative therapy?',
                'judgment': 'Pathologist\'s judgement of resected tumor margin',
                'grading': 'Grading of resection',
                'necrosis': 'Extent of necrosis in %',
                'mib_of_sarcoma': 'Proliferation index Mib if sarcoma (%)',
                'mitotic': 'Mitotic count',
                'closest_margin': 'Biological barrier to closest margin?',
                'closest_distance': 'Closest distance to margin (mm)',
                
            },
            'who': 'WHO Diagnosis Code',
            'comment': 'Comment of pathologist',
            'report': 'Report of pathologist for resected specimen (upload)',
            'report_ner': 'report_pathologist_resected_specimen_upload_ner', 
            'change': 'Did diagnosis change from biopsy?',


    },

    'surgery': {
            'entry_type': '*therapy',
            'date': 'Date of surgery',
            'type': '*surgery',
            'details': {
                'indications': 'Indications for surgery',
                'max_dimension': 'Largest tumor dimension (mm)',
                'judgment': 'Surgeon\'s judgement of resected tumor margin',
                'side': 'Side (surgery)', 
                'anatomic_region': 'Anatomic Region Code Surgery',
                'reconstruction': 'Reconstruction codes',
                'resection': 'Resection codes',
                'complexity': 'Complexity of surgery / Involved disciplines',
                'complexity_number': 'Number of disciplines involved (calculated)',
            
            },
            
            'report': 'Report for Surgery (upload)',
            'report_ner': 'report_for_surgery_upload_ner'

    },

    'radiation_oncology': {
            'entry_type': '*therapy',
            'date': 'Start of RadOnc',
            'type': '*radiation_oncology',
            'date_end': 'End of RadOnc',
            'details': {
                'dose': 'Total dose: How many Grays?',
                'number_fractions': 'Number of fractions',
                'ptv_volume': 'PTV volume (cm³)',
                'gtv_volume': 'GTV volume (cm³)',
                'additional_treatment': 'Additional, and concurrent treatments:',
            },
            'comments': 'Comments (radiation oncologist)',
            'planning': 'Planning / color wash (upload)',
            'report': 'Report for radiation oncology (upload)',
            'report_ner': 'report_radiation_oncology_upload_ner'
    },

    'chemotherapy': {
            'entry_type': '*therapy',
            'date': 'Date of surgery',
            'type': '*chemotherapy',
        
            'details': {
                'substances': 'Name of substances?',
                'number_cycles_executed': 'Number of cycles executed',
                'number_cycles_planned': 'Number of cycles planned',
                'reason_discontinuation': 'Reason for discontinuation:',

            },
            'type_bone_sarcoma': 'Bone sarcoma:',
            '5_years': 'Sarculator prOS 5 years:',
            '10_years': 'Sarculator prOS 10 years:',
            'cumulative_5_years': 'Cumulative incidence distant metastases at 5 years:',
            'cumulative_10_years': 'Cumulative incidence distant metastases at 10 years:',
            'best_response': 'Best treatment response',
            'reason': 'Reason for chemotherapy / systemic treatment',
            'comments': 'Comments (chemotherapy)',
  
            'report': 'Report for chemotherapy (upload)',
            'report_ner': 'report_for_chemotherapy_upload'

    },



    'outcomes_final': {
        'status_last_patient_contact_information': 'Status at last patient contact/information',
        'date_last_patient_contact_information': 'Date of last patient contact/information (highest of 725)',
        'date_of_initial_diagnosis': 'Entry date (dd.mm.yyyy)',
    },


    'diagnosis_n': [
        'Date of initial diagnosis',
        'Date of biopsy',
        'Local situation', 
        'Type',
        'Date of pathology report',
        'Date of first local recurrence (at follow up)',
        'Date of first local recurrence (lowest of 666 and 666A)',
        'Date of first local recurrence (lowest of 666A)',
        'Date of first local recurrence (lowest of 666)',
        
        'Anatomic Region Code',
        'Anatomic region code grouping (calculated)',
        'Date of systemic recurrence / metastasis',
        'Date of further systemic recurrences',

        
        'Date (highest of 725 and 100 copied to A0)',
        'Date of last patient contact/information [1]',
        'Date of first local recurrence (lowest of 666 and 666A)',
        'Date of initial radiology exam (lowest)',
        'Date of first local recurrence (at follow up) (lowest of 666)',
        'Date of first local recurrence (lowest of 666)',
        'Date of biopsy (lowest of 806)',
        'Date of initial radiology exam',
        'Date of pathology report (lowest of 1143)',
        'Date of surgery (lowest of 717)',
        'Date of first local recurrence (at follow up) (lowest of 666)',
        # Sarcoma Board
        'Date of SarcomaBoard presentation (highest 100)',
        'QI-18.2: Decision regarding surgery (copy of 797)',
        'QI-18.3: Decision regarding surgery (copy of 797)',
        'QI-18.4: Decision regarding surgery (copy of 799)',
        #
        '100A: Date of SarcomaBoard presentation (100 copied if 6581=yes)',
        'Date of biopsy',
        'Date of initial diagnosis',
        'Date of local recurrence',
        'Date of first systemic recurrence (at follow up)',
        'Date of 1° metastasis',
        'Date of systemic recurrence / metastasis',
        'Date of further systemic recurrences',
        'Metastasis at FollowUp',
        'Initials',
        'Please specify tumor simulator (0)',
        'Get Lowest Date of Date of initiation treatment',
        'Please specify tumor simulator',
        'Size A (in mm)',
        'Size B (in mm)',
        'Size C (in mm)',
        'suggestion how to proceed',
        
        'Further diagnostics',
        'Grading of biopsy',
        'Grading of resection',
        'Disease progression local or systemic?',
        'Disease progression (primary treatment)',
        'Disease progression (1st systemic recurrence)',
        'Disease progression (2+ recurrences)',
        'Presence of metastasis',
        'Proliferation index Mib if sarcoma (%)',
        'Mitotic count',
        'Extent of necrosis in %',
        'Pathologist\'s judgement of resected tumor margin',
        'Location of first local recurrence (at follow up)',
        'Location of first systemic recurrence (at follow up)',
        'Location of further systemic recurrence',
        'Anatomic Region Code systemic recurrence / metastasis',
        'Anatomic Region Code 1° metastasis',
        'Location of systemic recurrence / metastasis',
        'Location of 1° metastasis',
        'Location of disease progression (primary treatment)',
        'Anatomic Region Code systemic recurrence / metastasis at follow up (at follow up)',
        'Report of pathologist (biopsy) (upload)',
        'Report of pathologist for resected specimen (upload)',
        'Comment of pathologist',
        'Site of metastasis', 
        'Verdichtung R1 (834)',
        'First Time presentation with Metastasis (619=1 and 648=1)',
        'WHO Diagnosis Code (from outside SSN)',
        'WHO Diagnosis Code',
        'WHO Diagnosis Code (pathology)',
        'ICD-O Localisation',
        'ICD-O Histology',
        'Diagnosis (ICD 10)',
        'Initial radiology report',
        'Radiology report (important for SB)',
        'Summary decision / further strategy', 
        'Decision regarding surgery',
        'Decision regarding surgery (copy of 797)',
        'Decision regarding surgery (copy of 799)',
        'Comment regarding surgery:',
        'Decision regarding radiation therapy',
        'Comment regarding radiation therapy:',
        'Decision regarding chemotherapy / systemic drug therapy',
        'Comment regarding chemotherapy / systemic drug therapy:',
        'Initial size A (in mm)',
        'Initial size B (in mm)',
        'Initial size C (in mm)',
        'Size A (in mm) (calculated)',
        'Size B (in mm) (calculated)',
        'Size C (in mm) (calculated)',
        'Size A (in mm)',
        'Size B (in mm)',
        'Size C (in mm)',
        'Diagnosis malignant/benign? (calculated)',
        'Best treatment response',
        'Diagnosis (ICD 10)',
        'PTV volume (cm³)',
        'GTV volume (cm³)',
        'Anatomic region (free text)'
        
        'Read by reference pathologist? (biopsy)',
        'Read by reference pathologist? (pathology)',
        
        'Pathologist (pathology)',
        'Comment of pathologist',
        'Patient history (clinics, therapy, up to now)',
        'Participants at SB',
        'Pathology report (important for SB)',

        
        'Type of biopsy',
        'Local recurrence',
        'Reason for chemotherapy / systemic treatment',
        'Reason for follow up presentation',
        'Reason for chemotherapy / systemic treatment (calculated)',
        'Sarculator prOS 5 years:',
        'Sarculator prOS 10 years:',
        'Cumulative incidence distant metastases at 5 years:',
        'Cumulative incidence distant metastases at 10 years:',
        'Initial radiology report',
        
        'Biological barrier to closest margin?',
        'Biopsy was before first treatment per patient',
        'Bone sarcoma:',
        'Please specify other bone sarcoma', 
        'Closest distance to margin (mm)',
        'Comment regarding surgery:',
        'Comment regarding radiation therapy:',
        'Comment regarding chemotherapy / systemic therapy:',
        'Comment of pathologist',
        'Comments',
        'Comments (radiation oncologist)',
        
        'Did diagnosis change from biopsy?',
        'Difference (in days) of First Treatment and biopsy',
        'Difference (in days) of First Treatment 15184 and 100A',
        'Difference (in days) of local recurrence and tumor resection',
        'Difference of lowest 806 and lowest 1140',
        'Difference of 806A and 100A',
        'External PID',
        'Fast-Track',
        'Follow up SB presentation',
        'Follow up monitoring',
        'Follow up monitoring (copied 726)',
        'Gb-Nr.',
        'Initials',
        'Lap belt',
        'Largest tumor dimension (mm)',
        'Location of initial lesion?',
        'Main referral diagnosis',
        'Medical oncologist',
        'Mitotic count',
        'Comment regarding follow up monitoring',
        'Neo-adjuvant / preoperative therapy?',
        'New diagnostic codes (calculated)',
        'Number of biopsies',

        'Number of disciplines involved (calculated)',
        'Number of fractions',

        'Other diagnoses?',
        
        'Other tumor simulator (0)',
        'Pathologist (biopsy)',
        'Pathologist (pathology)',
        'Patient history (clinics, therapy, up to now)',
        'Participants at SB',
        'Please choose diagnosis/therapy for data entry:',
        'Please specify other autologous nerve reconstruction (recG.31)',
        'Please specify other bone reconstruction (recD.14)',
        'Please specify other chest / lung resection (resC.10)',
        'Please specify other extrapelvic anatomic region (D10.2)',
        'Please specify other extrapelvic anatomic region (D10.2) (SB)',
        'Please specify other free tissue transfer (recC.5)',
        'Please specify other intrapelvic anatomic region (D10.4)',
        'Please specify other intrapelvic anatomic region (D10.4) (SB)',
        'Please specify other intrathoracic (D19.4.5.)',
        'Please specify other metastasis (M.13.)',
        'Please specify other muscle flap (recB.10)',
        'Please specify other perforator flap (recB.9)',
        'Please specify other perforator flap (recC.4)',
        'Please specify other sequelae of 1° treatment (recE.7)',
        'Please specify other tendon transfer (recB.11)',
        'Please specify other treatment outside SSN',
        'Please specify other tumor simulator (0)',
        'Proliferation index Mib if sarcoma (%)',
        'PTV volume (cm³)',
        'Radiation oncologist 1',
        'Radiation therapy duration (calculated)',
        'Read by reference pathologist? (biopsy)',
        'Reason for chemotherapy / systemic treatment',
        'Reason for chemotherapy / systemic treatment (calculated)',
        'Reason for discontinuation:',
        'Reason for follow up presentation',
        'Report of pathologist (biopsy) (upload)',
        'Therapies carried out under this WHO diagnosis (calculated):',
        'Report of pathologist for resected specimen (upload)',
        'Type of hyperthermia',
        'Was the biopsy performed in the same center where the patient was operated?',
        'Which line?',
        'Type of radiology exam', 
        'Radiology report (important for SB)', 
        'If follow-up exam',

        ]
    }
    

renaming_dict = {
    'Patient ID (PID)': 'patient_id',
    'Location of initial lesion?': 'location_initial_lesion', 
    'External PID': 'external_pid',
    'Radiology report (important for SB)': 'radiology_report',
    'Anatomic Region Code': 'anatomic_region_code',
    'Year of entry': 'year_of_entry',
    'QI-5: Number of days from date of biopsy to presentation (calculated)': 'nr_days_from_date_of_biopsy_to_presentation',
    'Fast-Track': 'fast_track', 
    'Status at last patient contact/information': 'status_last_patient_contact_information',
    'Date of surgery':'date_of_surgery', 
    'Case number (FID)': 'case_number',
    'Date of initial radiology exam': 'date_of_initial_radiology_exam',
    'Calculate Date Diff biopsy/radiology (calculated)': 'calculate_date_diff_biopsy_radiology',
    'Local situation': 'local_situation',
    'Type of radiation therapy': 'type_of_radiation_therapy',
    'Entry date (dd.mm.yyyy)': 'entry_date',
    'WHO Diagnosis Code (pathology)': 'who_diagnosis_code_pathology',
    'Anatomic region code grouping (calculated)': 'anatomic_region_code_grouping',
    'Newest Date of SarcomaBoard': 'newest_date_of_sarcomaboard',
    'Year of birth (yyyy)': 'year_of_birth',
    'Follow up SB presentation': 'follow_up_sb_presentation',
    'Gender': 'gender',
    'Side (surgery)': 'side_surgery',
    'Pathology report (important for SB)': 'pathology_report_important_for_sb',
    'Total dose: How many Grays?': 'total_dose_grays',
    'Anatomic Region Code Surgery':'anatomic_region_code_surgery',
    'Responsible physician for 1st presentation': 'responsible_physician_first_presentation',
    'Get Lowest Date of Date of initiation treatment': 'get_lowest_date_of_date_of_initiation_treatment',
    'Initials': 'initials',
    'Cumulative incidence distant metastases at 10 years:' : 'cumulative_incidence_distant_metastases_10_years',
    'Cumulative incidence distant metastases at 5 years:': 'cumulative_incidence_distant_metastases_5_years',
    'Please specify "other institution"': 'other_institution',
    'Age: Admission Date minus 1 July of the year of birth (calculated)': 'age_at_admission',
    'Age class (calculated)': 'age_class',
    'Status': 'status',
    'Type of biopsy': 'type_of_biopsy', 
    'Please choose therapy for data entry:' :'therapy_type',
    'Clinic no.': 'clinic_no',
    'suggestion how to proceed': 'suggestion_how_to_proceed',
     'Neo-adjuvant / preoperative therapy?': 'neo_adjuvant_preoperative_therapy',
    'Type of radiology exam': 'type_of_radiology_exam', 
    'Diagnosis malignant/benign? (calculated)': 'diagnosis_malignant_benign',
    'Name of substances?': 'substances', 
    'Please specify other STS resection (resA.13)': 'please_specify_other_STS_resection_resA_13',
    'Metastasis at initial presentation': 'metastasis_at_initial_presentation',
    'Therapies carried out under this WHO diagnosis (calculated)': 'therapies_carried_out_under_this_WHO_diagnosis',
    'Date of biopsy (lowest of 806)': 'date_of_biopsy_lowest_806',
    'Date of first local recurrence (lowest of 666A)': 'date_of_first_local_recurrence_lowest_666A',
    'Date of initial radiology exam (lowest)': 'date_of_initial_radiology_exam_lowest',
    'Difference of lowest 806 and lowest 1140': 'difference_biopsy_radiology_exam',
    'Date of pathology report (lowest of 1143)': 'date_of_pathology_report_lowest_1143',
    'Date of surgery (lowest of 717)': 'date_of_surgery_lowest_717',
    'Date of first local recurrence (at follow up) (lowest of 666)': 'date_of_first_local_recurrence_followup_lowest_666',
    'Date of first local recurrence (lowest of 666 and 666A)': 'date_of_first_local_recurrence_lowest_666_666A',
    'Difference (in days) of local recurrence and tumor resection': 'difference_local_recurrence_tumor_resection',
    'Date of last patient contact/information (highest of 725)': 'date_of_last_patient_contact',
    'Date (highest of 725 and 100 copied to A0)': 'date_highest_725_100_copied_A0',
    'Date of SarcomaBoard presentation (highest 100)': 'date_of_sarcomaboard_presentation_highest',
    'Year of surgery': 'year_of_surgery',
    'Start of RadOnc': 'start_of_radonc',
    'Sarculator prOS 5 years:': 'sarculator_prOS_5_years',
    'Sarculator prOS 10 years:': 'sarculator_prOS_10_years',
    'Size A (in mm) (calculated)': 'size_a_calculated',
    'Size B (in mm) (calculated)': 'size_b_calculated',
    'Size C (in mm) (calculated)': 'size_c_calculated',
    'Difference (in days) of First Treatment 15184 and 100A': 'difference_days_first_treatment', 
    'Date of Surgery (dd.mm.yyyy)': 'date_of_surgery_dd_mm_yyyy',
    'Reason for chemotherapy / systemic treatment': 'reason_for_chemotherapy',
    '100A: Date of SarcomaBoard presentation (100 copied if 6581=yes)': 'date_of_sarcomaboard_presentation',
    'Difference of 806A and 100A': 'difference_date_biopsy_SB_presentation',
    'Date of whoops surgery': 'date_of_whoops_surgery',
    'Date of resection': 'date_of_resection',
    'First Time presentation with Metastasis (619=1 and 648=1)': 'first_timepresentation_with_metastasis',
    'Date of pathology report': 'date_of_pathology_report',
    'Date of first local recurrence (at follow up)': 'date_of_first_local_recurrence_followup',
    '666A: Date of first local recurrence (100 AND 1112=4)': 'date_of_first_local_recurrence_100_1112_4',
    'Date of first systemic recurrence (at follow up)': 'date_of_first_systemic_recurrence_followup',
    'Date of further systemic recurrences': 'date_of_further_systemic_recurrences',
    'Date of initial radiology exam': 'date_of_initial_radiology_exam',
    'Date of local recurrence': 'date_of_local_recurrence',
    'Date of biopsy': 'date_of_biopsy',
    'Please specify other sequelae of 1° treatment (resE.11)': 'please_specify_other_sequelae_of_first_treatment_resE_11',
    '806A: Date of biopsy (806 copied if 6581=yes)': 'date_of_biopsy_806_copied_6581_yes',
    'Date of systemic recurrence / metastasis': 'date_of_systemic_recurrence_metastasis',
    'Date of initial diagnosis': 'date_of_initial_diagnosis',
    'Date of 1° metastasis': 'date_of_first_metastasis',
    'Date of initiation treatment': 'date_of_initiation_treatment',
    'Date of surgery outside SSN (completed therapy)': 'date_of_surgery_outside_ssn_completed_therapy',
    'Date of radiotherapy outside SSN (completed therapy)': 'date_of_radiotherapy_outside_ssn_completed_therapy',
    'Date of chemotherapy outside SSN (completed therapy)': 'date_of_chemotherapy_outside_ssn_completed_therapy',
    'Date of surgery outside SSN (partial therapy)': 'date_of_surgery_outside_ssn_partial_therapy',
    'Date of radiotherapy outside SSN (partial therapy)': 'date_of_radiotherapy_outside_ssn_partial_therapy',
    'Date of chemotherapy outside SSN (partial therapy)': 'date_of_chemotherapy_outside_ssn_partial_therapy',
    'End of RadOnc': 'end_of_radonc',
    'Start date': 'start_date',
    'End date': 'end_date',
    'Op-No.': 'op_no',
    'Record initial size of lesion': 'record_initial_size_of_lesion',
    'Number of days from first contact with patient to date of SarcomaBoard presentation (calculated)': 'nr_days_from_first_contact_to_sarcoma_presentation',
    'Resection codes': 'resection_code',
    'Metastasis at FollowUp': 'metastasis_at_followup',
    'Reason for radiation therapy': 'reason_for_radiation_therapy',
    'Drug therapy duration (calculated)': 'drug_therapy_duration',
    'QI-1: radiology before biopsy? (calculated)': 'radiology_before_biopsy',
    'QI-2: Time (in days) from 1st patient contact to biopsy': 'time_days_first_contact_biopsy',
    'QI-1.1: Initial radiology report existing? (calculated)': 'initial_radiology_report_existing',
    'QI-17.1: Metastasis at inital presentation exists': 'metastasis_initial_presentation_exists',
    'QI-17.2: Metastasis at FollowUp exists': 'metastasis_followup_exists',
    'QI-18: Status at last patient contact/information (dort wo höchstes Datum 725)': 'status_last_patient_contact_highest_date',
    'QI-18.1: Follow up monitoring (copied 726)': 'follow_up_monitoring_copied',
    'QI-18.2: Decision regarding surgery (copy of 797)': 'decision_regarding_surgery_18_2',
    'QI-18.3: Decision regarding surgery (copy of 797)': 'decision_regarding_surgery_18_3',
    'QI-18.4: Decision regarding surgery (copy of 799)': 'decision_regarding_surgery_18_4',
    'QI-16: Local recurrence within 1st year of tumor resection (Bone)': 'local_recurrence_within_1_year_tumor_resection_bone',
    'QI-6: Biopsy was before first treatment per patient': 'biopsy_before_first_treatment',
    'QI-9: Time (in days) from SarcomaBoard until initiation of treatment': 'time_from_sarcomaboard_initiation_to_treatment',
    'QI-15: local relapse? (calculated)': 'qi15_local_relapse',
    'QI-13: Reason for chemotherapy / systemic treatment (calculated)': 'qi13_reason_chemotherapy_systemic_treatment',
    'QI-14: Reason for chemotherapy / systemic treatment (calculated)': 'qi14_reason_chemotherapy_systemic_treatment',
    'QI-3: Number of biopsies': 'number_of_biopsies',
    'QI-5: Time (in days) from biopsy until SarcomaBoard presentation': 'time_from_biopsy_to_sarcomaboard_presentation',
    'QI-4: Time from biopsy to establishing diagnosis (in days)': 'time_from_biopsy_to_establishing_diagnosis',
    'QI-7: Was the biopsy performed in the same center where the patient was operated?': 'qi7_biopsy_same_center_as_operation',
    'QI-11: Reason for radiation therapy preoperative (calculated)': 'reason_radiation_therapy_preoperative',
    'QI-12: Reason for radiation therapy postoperative (calculated)': 'reason_radiation_therapy_postoperative',
    'QI-1: preoperative radiation therapy? (Patient)': 'preoperative_radiation_therapy_patient',
    'QI-2: Number of days from first contact patient to date of biopsy (calculated)': 'qi2_number_of_days_first_contact_biopsy',
    'QI-18: Date of last patient contact isnotEmpty (for transcode)': 'qi18_date_last_patient_contact_isnotempty',
    'QI-18: Date of last patient contact/information (berechnet)': 'qi18_date_last_patient_contact_information_berechnet',
    'Number of intervention: How many interventions does the case count? (calculated)': 'number_of_interventions_case_count',
    'Number of operations: How many operations does the case count? (calculated)': 'number_of_operations_case_count',
    'Initial size A (in mm)': 'initial_size_a',
    'Initial size B (in mm)': 'initial_size_b',
    'Initial size C (in mm)': 'initial_size_c',
    'Size A (in mm)': 'size_a_mm',
    'Size B (in mm)': 'size_b_mm',
    'Size C (in mm)': 'size_c_mm',
    'Read by reference pathologist? (biopsy)': 'read_by_reference_pathologist', 
    'Grading of biopsy': 'grading_of_biopsy',
    'Grading of resection': 'grading_of_resection',
    'Disease progression local or systemic?': 'disease_progression_local_or_systemic',
    'Disease progression (primary treatment)': 'disease_progression_primary_treatment',
    'Disease progression (1st systemic recurrence)': 'disease_progression_first_systemic_recurrence',
    'Disease progression (2+ recurrences)': 'disease_progression_multiple_recurrences',
    'Presence of metastasis': 'presence_of_metastasis',
    'Proliferation index Mib if sarcoma (%)': 'proliferation_index_mib_sarcoma',
    'Mitotic count': 'mitotic_count',
    'Extent of necrosis in %': 'extent_of_necrosis_percent',
    'Closest distance to margin (mm)': 'closest_distance_to_margin_mm',
    'Biological barrier to closest margin?': 'biological_barrier_to_closest_margin',
    'Pathologist\'s judgement of resected tumor margin': 'pathologist_judgement_resected_tumor_margin',
    'Location of first local recurrence (at follow up)': 'location_first_local_recurrence_followup',
    'Location of first systemic recurrence (at follow up)': 'location_first_systemic_recurrence_followup',
    'Location of further systemic recurrence': 'location_further_systemic_recurrence',
    'Anatomic Region Code systemic recurrence / metastasis': 'anatomic_region_code_systemic_recurrence_metastasis',
    'Anatomic Region Code 1° metastasis': 'anatomic_region_code_first_metastasis',
    'Location of systemic recurrence / metastasis': 'location_systemic_recurrence_metastasis',
    'Report of pathologist (biopsy) (upload)': 'report_pathologist_biopsy_upload',
    'Report of pathologist for resected specimen (upload)': 'report_pathologist_resected_specimen_upload',
    'Comment of pathologist': 'comment_of_pathologist',
    'Specify current status': 'current_status',
    'WHO Diagnosis Code (from outside SSN)': 'who_diagnosis_code_outside_ssn',
    'WHO Diagnosis Code': 'who_diagnosis_code',
    'ICD-O Localisation': 'icd_o_localisation',
    'ICD-O Histology': 'icd_o_histology',
    'Diagnosis (ICD 10)': 'diagnosis_icd_10',
    'Initial radiology report': 'initial_radiology_report',
    'Decision regarding surgery': 'decision_regarding_surgery',
    'Decision regarding radiation therapy': 'decision_regarding_radiation_therapy',
    'Decision regarding chemotherapy / systemic drug therapy': 'decision_regarding_chemotherapy_systemic_therapy',
    'Main referral diagnosis': 'main_referral_diagnosis',
    'Best treatment response': 'best_treatment_response',
    'Number of fractions': 'number_of_fractions',
    'PTV volume (cm³)': 'ptv_volume_cm3',
    'GTV volume (cm³)': 'gtv_volume_cm3',
    'Number of sessions': 'number_of_sessions',
    'Temperature': 'temperature',
    'Duration of session (in minutes)': 'duration_of_session_minutes',
    'Planning / color wash (upload)': 'planning_color_wash_upload',
    'Type of hyperthermia': 'type_of_hyperthermia',
    'Radiation therapy duration (calculated)': 'radiation_therapy_duration_calculated',
    'Comments': 'comments',
    'Comments (radiation oncologist)': 'comments_radiation_oncologist',
    'Report for radiation oncology (upload)': 'report_radiation_oncology_upload',
    'Pathologist (biopsy)': 'pathologist_biopsy',
    'Pathologist (pathology)': 'pathologist_pathology',
    'Patient history (clinics, therapy, up to now)': 'patient_history',
    'Participants at SB': 'participants_at_sb',
    'E-Mail Notification Tool': 'email_notification_tool',
    '[WS-IDENT] COMPANY Interface Operator:': 'company_interface_operator',
    '[WS-IDENT] SOFTWARE Interface Operator:': 'software_interface_operator',
    '[WS-IDENT] TRSF VERSION Interface Operator:': 'trsf_version_interface_operator',
    'Export to AdjumedAnalyze': 'export_to_adjumed_analyze',
    'Last Generation Saved': 'last_generation_saved',
    'Summary files (upload)': 'summary_files_upload',
    'Follow up monitoring': 'follow_up_monitoring',
    'Other diagnoses?': 'other_diagnoses',
    'Surgery number': 'surgery_number',
    'Specify treatment outside SwissSarcomaNetwork': 'treatment_outside_ssn',
    'Type of treatment outside SwissSarcomaNetwork (completed therapy)': 'type_of_treatment_outside_ssn_completed',
    'Type of treatment outside SwissSarcomaNetwork (partial therapy)': 'type_of_treatment_outside_ssn_partial',
    'Specify other': 'specify_other',
    'Report for Surgery (upload)': 'report_for_surgery_upload',
     'Report for chemotherapy (upload)':'report_for_chemotherapy_upload', 
    'Specify other abdominal resection (resD.15)': 'specify_other_abdominal_resection',
    'Specify other autologous nerve reconstruction (recG.31)': 'specify_other_autologous_nerve_reconstruction',
    'Specify other bone reconstruction (recD.14)': 'specify_other_bone_reconstruction',
    'Specify other bone resection (resB.86)': 'specify_other_bone_resection',
    'Specify other chest / lung resection (resC.10)': 'specify_other_chest_lung_resection',
    'Specify other extrapelvic anatomic region (D10.2)': 'specify_other_extrapelvic_anatomic_region',
    'Specify other free tissue transfer (recC.5)': 'specify_other_free_tissue_transfer',
    'Specify other intrapelvic anatomic region (D10.4)': 'specify_other_intrapelvic_anatomic_region',
    'Specify other intraabdominal reconstruction (recI.6)': 'specify_other_intraabdominal_reconstruction',
    'Specify other intrathoracic (D19.4.5.)': 'specify_other_intrathoracic',
    'Specify other metastasis (M.13.)': 'specify_other_metastasis',
    'Specify other muscle flap (recB.10)': 'specify_other_muscle_flap',
    'Specify other perforator flap (recB.9)': 'specify_other_perforator_flap',
    'Specify other sequelae of 1° treatment (recE.7)': 'specify_other_sequelae_first_treatment',
    'Specify other STS resection (resA.13)': 'specify_other_sts_resection',
    'Specify other tendon transfer (recB.11)': 'specify_other_tendon_transfer',
    'Specify other treatment outside SSN': 'specify_other_treatment_outside_ssn',
    'Specify other tumor simulator (0)': 'specify_other_tumor_simulator',
    'Radiology has taken place (system) (copy ebene)': 'radiology_taken_place_system_copy_ebene',
    'Lap belt': 'lap_belt',
    'Type of initial radiology exam': 'type_initial_radiology_exam',
    'Get Lowest Date of Date of initial radiology': 'get_lowest_date_of_date_of_initial_radiology',
    'First Treatment (lowest of 717 or 767 or 845)': 'first_treatment_date',
    'Number of cycles planned': 'number_of_cycles_planned',
    'Number of cycles executed': 'number_of_cycles_executed',
    'Complexity of surgery / Involved disciplines': 'complexity_of_surgery', 
    'Start of chemotherapy / systemic treatment': 'start_of_chemotherapy',
    'End of chemotherapy / systemic treatment': 'end_of_chemotherapy',
    'Summary decision / further strategy': 'summary_decision_further_strategy',
    'Number of disciplines involved (calculated)':'number_of_disciplined_involved',
    "Surgeon's judgement of resected tumor margin": 'surgeon_judgement_resected_tumor_margin',
    "Date of last patient contact/information": 'date_of_last_patient_contact_highest',
    'Record additional ragiology exams': 'record_additional_radiology_exams',
}



data_format_dict = {
    'patient_id': str,
    'external_pid': str,
    'Status at last patient contact/information': int,
    'fast_track': bool,
    'resection_code': str,
    'suggestion_how_to_proceed': str,
    'pathology_report_important_for_sb': str,
    'surgeon_judgement_resected_tumor_margin': str,
    'year_of_entry': int,
    'anatomic:region_code': str,
    'side_surgery': int,
    'case_number': int,
    'clinic_no_1': int,
    'calculate_date_diff_biopsy_radiology':int,
    'type_of_biopsy':int, 
    'local_situation': int,
    'location_initial_lesion': int, 
    'number_of_cycles_planned':int,
    'number_of_cycles_executed':int, 
    'complexity_of_surgery':int,
    'date_of_initial_radiology_exam': 'datetime',
    'start_of_chemotherapy': 'datetime',
    'end_of_chemotherapy':'datetime', 
    'entry_date': 'datetime',
    'reason_radiation_therapy_preoperative': int,
    'reason_radiation_therapy_postoperative':int,
    'get_lowest_date_of_date_of_initial_radiology':'datetime',
    'op_no':int, 
    'who_diagnosis_code_pathology':str,
    'substances':int,
    'year_of_birth': int,
    'difference_date_biopsy_SB_presentation': int,
    'gender': int,
    'date_of_last_patient_contact_highest': 'datetime',
    'surgery_number': int,
    'responsible_physician_first_presentation': str,
    'initials': str,
    'other_institution': str,
    'age_at_admission': int,
    'age_class': int,
    # TODO: mak'Report for Surgery (upload)'e sure therapy type is int.
    'therapy_type': int,

    'month_of_entry': int,
    'weekday_of_entry': int,
    'therapies':int, 
    'status': int,
    'clinic_no': int,
    'anatomic_region_code_surgery':str,
    'date_of_surgery':'datetime',
    'type_initial_radiology_exam':int,
    'date_first_contact_to_sarcoma_presentation':'datetime',
    'nr_days_from_first_contact_to_sarcoma_presentation': int, 
    'time_from_sarcomaboard_initiation_to_treatment': int,
    'newest_date_of_sarcomaboard':'datetime',
    'date_of_biopsy_lowest_806': 'datetime',
    'date_of_first_local_recurrence_lowest_666A': 'datetime',
    'date_of_initial_radiology_exam_lowest': 'datetime',
    'difference_lowest_806_1140': int,
    'date_of_pathology_report_lowest_1143': 'datetime',
    'date_of_surgery_lowest_717': 'datetime',
    'date_of_first_local_recurrence_followup_lowest_666': 'datetime',
    'date_of_first_local_recurrence_lowest_666_666A': 'datetime',
    'difference_local_recurrence_tumor_resection': int,
    'date_of_last_patient_contact_highest_725': 'datetime',
    'date_of_last_patient_contact': 'datetime',
    'get_lowest_date_of_date_of_initiation_treatment': 'datetime',
    'date_highest_725_100_copied_A0': 'datetime',
    'date_of_sarcomaboard_presentation_highest_100': 'datetime',
    'first_treatment_date': 'datetime',
    'year_of_surgery': int,
    'start_of_radonc': 'datetime',
    'date_of_surgery_ddmmyyyy': 'datetime',
    'date_of_sarcomaboard_presentation_100_copied_6581_yes': 'datetime',
    'difference_806A_100A': int,
    'date_of_whoops_surgery': 'datetime',
    'date_of_resection': 'datetime',
    'date_of_pathology_report': 'datetime',
    'date_of_first_local_recurrence_followup': 'datetime',
    'date_of_first_local_recurrence_100_1112_4': 'datetime',
    'date_of_first_systemic_recurrence_followup': 'datetime',
    'date_of_further_systemic_recurrences': 'datetime',
    'date_of_initial_radiology_exam': 'datetime',
    'date_of_local_recurrence': 'datetime',
    'date_of_biopsy': 'datetime',
    'date_of_biopsy_806_copied_6581_yes': 'datetime',
    'date_of_systemic_recurrence_metastasis': 'datetime',
    'date_of_initial_diagnosis': 'datetime',
    'date_of_first_metastasis': 'datetime',
    'date_of_initiation_treatment': 'datetime',
    'date_of_surgery_outside_ssn_completed_therapy': 'datetime',
    'date_of_radiotherapy_outside_ssn_completed_therapy': 'datetime',
    'date_of_chemotherapy_outside_ssn_completed_therapy': 'datetime',
    'date_of_surgery_outside_ssn_partial_therapy': 'datetime',
    'date_of_radiotherapy_outside_ssn_partial_therapy': 'datetime',
    'date_of_chemotherapy_outside_ssn_partial_therapy': 'datetime',
    'end_of_radonc': 'datetime',
    'start_date': 'datetime',
    'end_date': 'datetime',
    'radiology_before_biopsy': bool,
    'time_days_first_contact_biopsy': int,
    'qi1_1_initial_radiology_report_existing': str,
    'informed_patient_consent_available': str,
    'qi17_1_metastasis_initial_presentation_exists': str,
    'qi17_2_metastasis_followup_exists': str,
    'qi18_status_last_patient_contact_highest_date_725': str,
    'qi18_1_follow_up_monitoring_copied_726': str,
    'qi18_2_decision_regarding_surgery_copy_797': str,
    'qi18_3_decision_regarding_surgery_copy_797': str,
    'qi18_4_decision_regarding_surgery_copy_799': str,
    'qi16_local_recurrence_within_1_year_tumor_resection_bone': str,
    'qi6_biopsy_before_first_treatment': str,
    'qi9_time_days_sarcomaboard_initiation_treatment': int,
    'qi15_local_relapse': int,
    'qi13_reason_chemotherapy_systemic_treatment': int,
    'qi14_reason_chemotherapy_systemic_treatment': int,
    'qi3_number_of_biopsies': int,
    'qi5_time_days_biopsy_sarcomaboard_presentation': int,
    'qi4_time_days_biopsy_establishing_diagnosis': int,
    'qi7_biopsy_same_center_as_operation': str,
    'qi11_reason_radiation_therapy_preoperative': str,
    'qi12_reason_radiation_therapy_postoperative': str,
    'qi1_preoperative_radiation_therapy_patient': str,
    'qi1_radiology_before_biopsy_calculated': str,
    'qi2_number_of_days_first_contact_biopsy': int,
    'qi18_date_last_patient_contact_isnotempty': 'datetime',
    'qi18_date_last_patient_contact_information_berechnet': 'datetime',
    'number_of_interventions_case_count': int,
    'number_of_operations_case_count': int,
    'initial_size_a': float,
    'initial_size_b': float,
    'initial_size_c': float,
    'size_a_mm': float,
    'size_b_mm': float,
    'size_c_mm': float,
    'nr_days_from_date_of_biopsy_to_presentation': int,
    'grading_of_biopsy': int,
    'grading_of_resection': str,
    'disease_progression_local_or_systemic': str,
    'disease_progression_primary_treatment': str,
    'disease_progression_first_systemic_recurrence': int,
    'disease_progression_multiple_recurrences': str,
    'presence_of_metastasis': int,
    'proliferation_index_mib_sarcoma': int,
    'mitotic_count': int,
    'extent_of_necrosis_percent': float,
    'closest_distance_to_margin_mm': float,
    'biological_barrier_to_closest_margin': str,
    'pathologist_judgement_resected_tumor_margin': str,
    'location_first_local_recurrence_followup': str,
    'location_first_systemic_recurrence_followup': str,
    'location_further_systemic_recurrence': str,
    'anatomic_region_code_systemic_recurrence_metastasis': str,
    'anatomic_region_code_first_metastasis': str,
    'location_systemic_recurrence_metastasis': str,
    'report_pathologist_biopsy_upload': str,
    'report_pathologist_resected_specimen_upload': str,
    'comment_of_pathologist': str,
    'current_status': str,
    'who_diagnosis_code_outside_ssn': str,
    'who_diagnosis_code': str,
    'icd_o_localisation': str,
    'icd_o_histology': str,
    'diagnosis_icd_10': str,
    'initial_radiology_report': str,
    'decision_regarding_surgery': int,
    'decision_regarding_radiation_therapy': str,
    'decision_regarding_chemotherapy_systemic_therapy': str,
    'main_referral_diagnosis': str,
    'best_treatment_response': str,
    'number_of_fractions': int,
    'ptv_volume_cm3': float,
    'gtv_volume_cm3': float,
    'total_dose_grays': float,

    'number_of_sessions': int,
    'temperature': float,
    'duration_of_session_minutes': int,
    'planning_color_wash_upload': str,
    'type_of_hyperthermia': str,
    'radiation_therapy_duration_calculated': int,
    'comments': str,
    'comments_radiation_oncologist': str,
    'report_radiation_oncology_upload': str,
    'pathologist_biopsy': int,
    'pathologist_pathology': str,
    'patient_history': str,
    'participants_at_sb': int,
    'number_of_biopsies':int,
    'email_notification_tool': str,
    'company_interface_operator': str,
    'software_interface_operator': str,
    'trsf_version_interface_operator': str,
    'export_to_adjumed_analyze': str,
    'consent_available_for': str,
    'last_generation_saved': str,
    'summary_files_upload': str,
    'follow_up_monitoring': str,
    'other_diagnoses': str,
    'treatment_outside_ssn': str,
    
    'type_of_treatment_outside_ssn_completed': str,
    'type_of_treatment_outside_ssn_partial': str,
    'specify_other': str,
    'specify_other_abdominal_resection': str,
    'specify_other_autologous_nerve_reconstruction': str,
    'specify_other_bone_reconstruction': str,
    'specify_other_bone_resection': str,
    'specify_other_chest_lung_resection': str,
    'specify_other_extrapelvic_anatomic_region': str,
    'specify_other_free_tissue_transfer': str,
    'specify_other_intrapelvic_anatomic_region': str,
    'specify_other_intraabdominal_reconstruction': str,
    'specify_other_intrathoracic': str,
    'specify_other_metastasis': str,
    'specify_other_muscle_flap': str,
    'specify_other_perforator_flap': str,
    'specify_other_sequelae_first_treatment': str,
    'specify_other_sts_resection': str,
    'specify_other_tendon_transfer': str,
    'specify_other_treatment_outside_ssn': str,
    'specify_other_tumor_simulator': str,
    'radiology_taken_place_system_copy_ebene': str,
    'send_message': str,
    'lap_belt': str,
    'anatomic_region_code_grouping':str,
    'date_of_sarcomaboard_presentation_highest':'datetime', 
    'date_of_sarcomaboard_presentation':'datetime',
    'get_lowest_date_of_date_of_initiation_treatment': 'datetime',
    'summary_decision_further_strategy': str,
    'size_a_calculated': float,
    'size_b_calculated': float,
    'size_c_calculated': float,
    'diagnosis_malignant_benign': int,
    'reason_for_chemotherapy': int, 
    'difference_days_first_treatment': int,
    'fast_track': bool,
    'follow_up_sb_presentation':int,
    'number_of_disciplined_involved': int,
    'read_by_reference_pathologist': int, 
    'type_of_radiology_exam': int, 
    'type_of_radiation_therapy':int, 
}
