services:
  ### DATABASE SERVICES ###
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    volumes:
      - mongo-data:/data/db
    ports:
      - "28017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  ### ETL SERVICE  ###
  etl:
    build: ./ETL
    container_name: etl_service
    depends_on:
      - mongo_db
    environment:
      MONGO_URI: "mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo_db:27017/?authSource=admin"
    volumes:
      - ./ETL:/app
    entrypoint: []
    command: ["tail", "-f", "/dev/null"]
    networks:
      - backend 
      
  ### MODEL TRAINING SERVICE ###
  model_training:
    build: ./Models
    container_name: model_training_service
    depends_on:
      - mongo_db
    environment:
      MONGO_URI: "mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo_db:27017/?authSource=admin"
    volumes:
      - ./Models:/app
      - saved_models:/app/saved_models
    command: ["tail", "-f", "/dev/null"]
    networks:
      - backend 
  ### INFERENCE & VISUALIZATION SERVICE ###
  inference_visualization:
    build: ./Inference
    container_name: inference_service
    depends_on:
      - mongo_db
      - model_training
    ports:
      - "8000:8000"  # FastAPI API
      - "8501:8501"  # Streamlit Dashboard
      - "8888:8888"  # Jupyter Notebook
    environment:
      MONGO_URI: "mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo_db:27017/?authSource=admin"
    volumes:
      - ./Inference:/app
      - saved_models:/app/saved_models
    command: ["tail", "-f", "/dev/null"]
    networks:
      - backend 

networks:
  backend:
    driver: bridge

volumes:
  mongo-data:
  saved_models:
